apiVersion: v1
kind: Namespace
metadata:
  name: enkap-production
  labels:
    istio-injection: enabled   # Otomatik mTLS sidecar enjeksiyonu
---
apiVersion: v1
kind: Namespace
metadata:
  name: enkap-staging
  labels:
    istio-injection: enabled
